### PR TITLE
Adding Sample

### PR DESCRIPTION
**Pull request by lanrongwen**
Adding some sample code to help people understand how to use the code outside of Home Assistant.

### CODE REVIEW

**Comment by lanrongwen** [comment]
Found a few small issues, will be doing some quick updates then I'll repost.

**Comment by teharris1** [comment]
Good idea. This was always intended to be broader than just HA so glad you are doing this.

**Comment by lanrongwen** [comment]
I think I still have a few more small tweaks but I'm getting closer.

**Comment by lanrongwen** [comment]
Figured it out, I was just staring at it too long on the temp checks.  It feels more consistent on the polling, but I haven't really touched that yet, so we'll see.  I think this is good for initial review/feedback.

**Comment by teharris1** [comment]
I will look at this tonight and try in my test environment. In the meantime you have some pylint issues (mostly line too long). Can you have a look at that?
Thanks

**Comment by lanrongwen** [comment]
Sorry about the lint test, thought I had caught them all.  :)

**Comment by teharris1** [comment]
@lanrongwen let me know if you want to reopen this. Given that it is a year old and not passing the tests. I am going to close this as stale.

**Pull request closed without merging**
