### PR TITLE
Refactored code

### PR DESCRIPTION
**Pull request by teharris1**
Too much to explain here :)

### CODE REVIEW

**Comment by teharris1** [comment]
Massive refactoring. Tested in my local environment with 27 devices of various forms.

**Comment by dakoellis** [comment]
Just want to put it out there that after getting both a new PLM and a new serial card, the code works great with the 2413S.  thanks for the work on this @teharris1!

**Comment by teharris1** [comment]
@nugget any chance you can test this / confirm it is OK to merge?  I know I can merge it but prefer to have some additional testing before I do.

**Comment by dakoellis** [comment]
@teharris1 does that mean this will be included in the next release of HASS?  Thanks again for all your work and help on this!

**Comment by teharris1** [comment]
We have to get the new version in to PyPi python repository first otherwise HA will not be able to find it during install. I am hopeful it will get into the next release but not 100% sure.

**Comment by nugget** [comment]
I mangled the README.md handling in the release, bumped to version 0.8.1 and then managed to mangle it a different way.  But, it's pushed to PyPi now (just with no project description) and I think I've got the pandoc stuff set back up properly so when we do 0.8.2 it will work properly.

**Comment by teharris1** [comment]
Excellent. Thank you. I just ran pip and got version 0.8.1!

**Pull request merged**
