### PR TITLE
Add ability to notify via callback when a device isn't responding

### PR DESCRIPTION
**Pull request by yombo**
I forgot to make a pull request for the notify when done starting up, but glad you found it and put it in the code.

Here's another callback to notify when a device isn't responding properly on startup.

### CODE REVIEW

**Comment by teharris1** [comment]
So looking at this again I have a couple of questions:
1) Why import Address? The callback template has to take an Address object but that implies it knows what an Address is. Would you be better off just passing back the string or byte value of the address? In this way, the callback function can choose to import and convert to an Address or use it as a string. Otherwise the receiving module is required to know the INSTEON Address type. 
2) What is your overall use case? Are you using this in Home Assistant or is there another front end you are working with? Love to learn how you intend to use it so I can help with the outcome. 

How comfortable are you with async programming? One of the change I have been considering is making most functions awaitable so that callbacks become less necessary. Do you have any thoughts on this?

**Comment by yombo** [comment]
Sorry for the delay. I was away on vacation. :-)

Both of your points make sense and shouldn't return an Address instance. I'll adjust and update the pull request. I'll make it just return the 'human' version with dotted notation.

I'm ok with async, but better with twisted deferred as that project i'm working on uses twisted matrix; however, it can interact with async just fine.

**Comment by yombo** [comment]
I have the changes ready, but now this API is inconsistent. The method "_update_subscribers()" and the property 'address' in states/__init__.py both return an Address instance and not a string (either human or hex).
 Which way do you want to handle this? Make everything return Address instances, hex strings, or human strings?  I'm fine with whatever your choose, but please choose one and lets stick with that. The worst thing is to return difference values when getting the same type of data.

**Comment by teharris1** [comment]
Great catch. Thanks. My vote would be hex since byte is primarily used for communication to and from  the device and human is for display purposes. Hex is unformatted but more friendly than byte.

**Comment by teharris1** [comment]
Thinking about it more, if the goal of the insteonplm project is to be an add-in module. I am not sure what the best approach is. Should the master program understand the insteonplm objects or not? Here is my adjusted view:
1) Returning Address means the main module calling insteonplm needs to know the underlying objects. This is required in any situation since the objects have to be interacted with in order to function.
2) Returning Human is a real obfuscation of the underlying objects all the way to the 'human' level.
3) Hex is in between
The more I think about it you may be right that returning Address makes more sense and let the main module decide what it wants to use it for.

**Comment by yombo** [comment]
I like returning the Address instance. Let me know if you have any questions before accepting this PR. This PR does contain two commits. One with the callback loop, and the second adding the reference the address since that is used to generate the argument to be sent to the callback.

**Comment by teharris1** [comment]
OK, I think we keep it with returning Address. Accepting the PR. Thanks for contributing.

**Pull request merged**
